spring.application.name=hemoscan-api
server.port=8080
spring.datasource.url=jdbc:h2:mem:hemoscandb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
app.jwt.secret=HemoScanAI_SuperSecretKey_2024_ChangeInProduction_MustBe256BitsLong
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:3000,http://localhost:8080